_wandb:
    value:
        cli_version: 0.17.5
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 35
                - 41
                - 49
                - 50
                - 51
                - 53
                - 54
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 35
                - 41
                - 49
                - 50
                - 51
                - 53
                - 54
                - 55
                - 71
            "3":
                - 2
                - 15
                - 23
                - 55
            "4": 3.9.18
            "5": 0.17.5
            "6": 4.26.1
            "8":
                - 5
            "12": 0.17.5
            "13": linux-x86_64
