log_tag: "mscoco-merge-label-test"
seed: 42

dataset:
  train_path: /data/SSD/coco/annotations/coco_karpathy_train.json
  val_path: /data/SSD/coco/annotations/coco_karpathy_val.json
  test_path: /data/SSD/coco/annotations/coco_karpathy_test.json
  img_path: /data/SSD/coco/images
  img_path_test: /data/SSD/coco/images
  log_path: res
  ratio: 1

model:
  num_dim: 512
  use_residual: False

train:
  # Basic
  max_epochs: 30 # Normally 6 for fine-tuning, 30 for training from scratch
  lr: 1e-5
  weight_decay: 5e-2
  betas: [0.9, 0.999]
  # Scheduler
  T_max: 30
  lr_min: 1e-9
  # Dataset
  batch_size: 128
  num_workers: 8
  log_interval: 50
  # Label update warm-up

eval:
  batch_size: 1024
  num_workers: 8

control:
  train: True
  val: True
  test: False
  save: False
  save_interval: 1
