log_tag: "flickr8k-merge-label-test"
seed: 42

dataset:
  train_path:
  val_path: data/flickr30k/test.json
  test_path: data/imp/test.json
  img_path: /data/SSD/flickr30k/images
  img_path_test: /data/SSD/unsplash/images_resize

model:
  num_dim: 512
  use_residual: False

train:
  # Basic
  max_epochs: 6
  lr: 1e-4
  weight_decay: 5e-2
  betas: [0.9, 0.999]
  # Scheduler
  T_max: 6
  lr_min: 1e-7
  # Dataset
  batch_size: 1024
  num_workers: 8
  log_interval: 25

eval:
  batch_size: 1024
  num_workers: 8

control:
  train: True
  val: True
  test: True
  save: True
  save_interval: 1
