wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721161557
    t:
      1:
      - 1
      - 5
      - 11
      - 35
      - 41
      - 49
      - 50
      - 51
      - 53
      - 54
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 35
      - 41
      - 49
      - 50
      - 51
      - 53
      - 54
      - 55
      - 71
      3:
      - 15
      - 23
      4: 3.9.18
      5: 0.17.4
      6: 4.26.1
      8:
      - 5
      13: linux-x86_64
